### ISSUE TITLE
`User not found` leads to runtime exception

### ISSUE THREAD

**Issue by yegor256** [zerocracy/pages-action#131]
I found this problem [here](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419):

```
Octokit::Forbidden: GET https://api.github.com/user/29139614: 403 - Resource not accessible by integration // See: https://docs.github.com/rest
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/middleware/quota.rb:48:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:[99](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419#step:6:100):in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/users.rb:34:in `user'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/octo.rb:115:in `user_name_by_id'
	/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'Octokit::Forbidden: GET https://api.github.com/user/29139614: 403 - Resource not accessible by integration // See: https://docs.github.com/rest
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/middleware/quota.rb:48:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:444:in `run_request'
	/usr/local/bundle/gems/faraday-2.10.1/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:[99](https://github.com/zerocracy/judges-action/actions/runs/10900854041/job/30249395419#step:6:100):in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/users.rb:34:in `user'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/fbe-0.0.53/lib/fbe/octo.rb:115:in `user_name_by_id'
	/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'
```

Probably, the user is deleted and that's why we fail.

**Comment by yegor256** [comment]
@Yegorov you are right, transferred

**Comment by yegor256** [comment]
@Yegorov maybe it's possible to check the presence of a user via GitHub API? Just ignoring _all_ client errors is not a good idea.

**Comment by Yegorov** [comment]
@yegor256 it was a false assumption that the user was deleted or not found
```
octo.user(29139614)
GET https://api.github.com/user/29139614
D: Octokit::Client.user(29139614) in 512ms
 =>
{:login=>"renovate[bot]",
 :id=>29139614,
```

If the user does not exist, then there must be an error: [`404 - Not Found`](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#404-not-found-for-an-existing-resource)
```
octo.user(11)
D: Octokit::Client.user(11) in 454ms
/home/artem/.rvm/gems/ruby-3.3.4/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/user/11: 404 - Not Found // See: https://docs.github.com/rest (Octokit::NotFound)
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-2.10.1/lib/faraday/middleware.rb:57:in `block in call'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-2.10.1/lib/faraday/response.rb:42:in `on_complete'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-2.10.1/lib/faraday/middleware.rb:56:in `call'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
        from /home/artem/.rvm/gems/ruby-3.3.4/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
        from /home/artem/projects2/zerocracy/fbe/lib/fbe/middleware/quota.rb:48:in `call'
```

Error `403 - Resource not accessible by integration` based on the documentation is related to [rate limiting](https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#rate-limit-errors):
> If you exceed your primary rate limit, you will receive a 403 Forbidden or 429 Too Many Requests response, and the x-ratelimit-remaining header will be 0. If you exceed a secondary rate limit, you will receive a 403 Forbidden or 429 Too Many Requests response and an error message that indicates that you exceeded a secondary rate limit.

We cannot find out why Github answered with this `403 Forbidden` error and not `429 Too Many Requests` because [there was no logger](https://github.com/zerocracy/fbe/blob/5f1cf77099c0ee7d6c4ab8e7506f13f7f5a2dcaf/lib/fbe/octo.rb#L94)

I propose to implement logging only answers with statuses of more than 400 to find out the cause of [this error](https://github.com/octokit/octokit.rb/blob/main/lib/octokit/error.rb#L100).
What do you think?

**Comment by yegor256** [comment]
@Yegorov I like the idea of making logging more verbose. Now, we use `Loog::NULL`, while `loog` is provided as an argument of `Fbe.octo`. This looks wrong. However, just passing `loog` instead of `Loog::NULL` may lead to very verbose log output. Try to fix this, but be aware of the problem: logs must not be noise when `loog` is `Loog::REGULAR`.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.35`

**Comment by VasilevNStas** [comment]
The root cause is in the `fbe` gem: `user_name_by_id` in `lib/fbe/octo.rb` did not handle `Octokit::Forbidden` (returned when a user is deleted).

Fixed in zerocracy/fbe#574 — `user_name_by_id` now rescues both `Octokit::NotFound` and `Octokit::Forbidden`, logs a warning and returns `nil`.

Once that PR is reviewed and merged, and a new version of the `fbe` gem is released, the `Gemfile` in this repo needs to be bumped to include the fix.

**Comment by VasilevNStas** [comment]
@yegor256 plz review

**Comment by morphqdd** [comment]
@yegor256, this looks stale — I checked current `master` and there's no `judges/add-user-names/` directory or any file matching `add-user-names.rb`/`user_name_by_id` anywhere in the repo anymore (confirmed via a full-repo search). The judge this issue references no longer exists, so there's nothing left to fix. Not picking this up.

**Comment by 0crat** [comment]
@yegorov Thanks for closing this issue! You've earned +4 points for this: +12 as a basis; -20 for 658 days of delay; +12 to give you at least something. Your running score is [+4](https://zerocracy.github.io/judges-action/zerocracy-vitals.html); don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too).
