### ISSUE TITLE
handle 404 when fetching GitHub user

### ISSUE THREAD

**Issue by Suban05** [zerocracy/pages-action#151]
@yegor256 I see it [here](https://github.com/zerocracy/judges-action/actions/runs/11257753258/job/31302737128)
```
Octokit::NotFound: GET https://api.github.com/user/13273243: 404 - Not Found // See: https://docs.github.com/rest
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/middleware.rb:57:in `block in call'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/response.rb:42:in `on_complete'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/middleware.rb:56:in `call'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:286:in `fetch'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:190:in `process'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:141:in `call!'
	/usr/local/bundle/gems/faraday-http-cache-2.5.1/lib/faraday/http_cache.rb:121:in `call'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/middleware/quota.rb:48:in `call'
	/usr/local/bundle/gems/faraday-retry-2.2.1/lib/faraday/retry/middleware.rb:153:in `call'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/rack_builder.rb:152:in `build_response'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/connection.rb:452:in `run_request'
	/usr/local/bundle/gems/faraday-2.12.0/lib/faraday/connection.rb:200:in `get'
	/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:156:in `request'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/connection.rb:19:in `get'
	/usr/local/bundle/gems/octokit-9.1.0/lib/octokit/client/users.rb:34:in `user'
	/usr/local/bundle/gems/verbose-0.0.2/lib/verbose.rb:48:in `method_missing'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/octo.rb:126:in `user_name_by_id'
	/home/judges/add-user-names/add-user-names.rb:31:in `block (2 levels) in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:96:in `block in consider'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:109:in `block (3 levels) in roll'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:123:in `block in each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/query.rb:69:in `block in each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/query.rb:58:in `each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/query.rb:58:in `each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:122:in `each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:142:in `block in each'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:189:in `elapsed'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:141:in `each'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:107:in `block (2 levels) in roll'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:65:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:73:in `block in txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase.rb:168:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/rules.rb:72:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/pre.rb:62:in `txn'
	/usr/local/bundle/gems/factbase-0.4.0/lib/factbase/looged.rb:63:in `txn'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:106:in `block in roll'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:105:in `catch'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:105:in `roll'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:95:in `consider'
	/home/judges/add-user-names/add-user-names.rb:30:in `block in <top (required)>'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:39:in `instance_eval'
	/usr/local/bundle/gems/fbe-0.0.72/lib/fbe/conclude.rb:39:in `conclude'
	/home/judges/add-user-names/add-user-names.rb:28:in `<top (required)>'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:60:in `load'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:60:in `block in run'
	/usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in `elapsed'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judge.rb:59:in `run'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:136:in `one_judge'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:113:in `block (3 levels) in cycle'
	/usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in `elapsed'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:112:in `block (2 levels) in cycle'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judges.rb:76:in `block in each_with_index'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judges.rb:67:in `block in each'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judges.rb:63:in `each'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judges.rb:63:in `each'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/judges.rb:75:in `each_with_index'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:110:in `block in cycle'
	/usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in `elapsed'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:108:in `cycle'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:72:in `block (2 levels) in run'
	<internal:kernel>:187:in `loop'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:67:in `block in run'
	/usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in `elapsed'
	/usr/local/bundle/gems/judges-0.26.1/lib/judges/commands/update.rb:66:in `run'
	/usr/local/bundle/gems/judges-0.26.1/bin/judges:39:in `block in run_it'
	/usr/local/bundle/gems/gli-2.21.5/lib/gli/command_support.rb:131:in `execute'
	/usr/local/bundle/gems/gli-2.21.5/lib/gli/app_support.rb:298:in `block in call_command'
	/usr/local/bundle/gems/gli-2.21.5/lib/gli/app_support.rb:311:in `call_command'
	/usr/local/bundle/gems/gli-2.21.5/lib/gli/app_support.rb:85:in `run'
	/usr/local/bundle/gems/judges-0.26.1/bin/judges:198:in `<top (required)>'
	/usr/local/bundle/bin/judges:25:in `load'
	/usr/local/bundle/bin/judges:25:in `<main>'
```
maybe we should check the existence of a user before calling `user_name_by_id`
https://github.com/zerocracy/pages-action/blob/83b466c7cabe4a95d604b3b89057a7362ee07d26/judges/add-user-names/add-user-names.rb#L31

**Comment by yegor256** [comment]
@Suban05 thanks for the report, but I don't think it's possible to "check the existence". Most probably, we should just handle this 404 error correctly and re-raise a proper exception, which is handled later correctly.

**Comment by 0crat** [comment]
@Suban05 Thank you for reporting a new bug! Your contribution is valuable in improving our project's quality. As per our team's policy, you've earned **8** points for this report. Your current balance is now [+116](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). We encourage you to continue [reporting](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) any issues you find in the repository that [don't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as expected. Your vigilance helps maintain our high standards, so [don't hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to bring any concerns to our attention.
